version: "3.9"

services:

  flask_app:
    build: ./app
    container_name: hrishi_flask_new
    ports:
      - "5000:5000"
    depends_on:
      - redis_db

  redis_db:
    image: redis:latest
    container_name: redis_db
    ports:
      - "6379:6379"
